name: Build & Deploy

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                browser: [ chromium, firefox, webkit ]
        
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Set up Bun
                uses: oven-sh/setup-bun@v2

            -   name: Get installed Playwright version
                id: playwright-version
                run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').dependencies['@playwright/test'].version)")" >> $GITHUB_ENV

            -   name: Cache playwright binaries
                uses: actions/cache@v3
                id: playwright-cache
                with:
                    path: |
                        ~/.cache/ms-playwright
                    key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

            -   name: Install dependencies
                run: bun install

            -   name: Install Playwright dependencies
                run: npx playwright install-deps ${{ matrix.browser }}
                if: steps.playwright-cache.outputs.cache-hit != 'true' || matrix.browser == 'webkit'

            -   name: Install Playwright browsers
                run: bunx playwright install ${{ matrix.browser }}
                if: steps.playwright-cache.outputs.cache-hit != 'true'

            -   name: Run Playwright tests for ${{ matrix.browser }}
                run: bunx playwright test --project=${{ matrix.browser }}

    build-and-deploy:
        runs-on: ubuntu-latest
        needs: test
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

        permissions:
            contents: write

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Set up Bun
                uses: oven-sh/setup-bun@v2

            -   name: Install dependencies
                run: bun install

            -   name: Build project
                run: bun -b run build

            -   name: Deploy to BunnyCDN
                uses: ayeressian/bunnycdn-storage-deploy@v2.2.5
                with:
                    source: "dist"
                    destination: "/"
                    storageZoneName: "${{ secrets.STORAGE_NAME }}"
                    storagePassword: "${{ secrets.STORAGE_PASSWORD }}"
                    accessKey: "${{ secrets.STORAGE_KEY }}"
                    pullZoneId: "${{ secrets.ZONE_ID }}"
                    upload: "true"
                    remove: "true"
                    purgePullZone: "true"
